### ISSUE TITLE
imagick fails in PHP 7.2; php.ini problem?

### ISSUE THREAD

**Issue by tmb-github** [mkoppanen/imagick#224] opened 2017-12-29 15:13 UTC
In PHP 7.2, the extensions definitions in the php.ini file do not require the initial "php_" nor the extension ".dll". So, for the php_imagick.dll file to be specified as an extension in the php.ini file, in theory you only need to add:

`extension=imagick`

Not:

`extension=php_imagick.dll`

...although, for backward compatibility, the instructions at the top of the file indicate that the older, full-name specification will still work but will be deprecated at some point.

Using either form above does not work. When using the new form (`extension=imagick`) and when I start my XAMPP Apache server, I receive this error:

> [23-Dec-2017 15:55:49 UTC] PHP Warning: PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\xampp\php\ext\imagick (The specified module could not be found.
> ), C:\xampp\php\ext\php_imagick.dll (The specified procedure could not be found.
> )) in Unknown on line 0
> 

Using the older form of the extension initialization, (`extension=php_imagick.dll`), the error message becomes:

> [23-Dec-2017 15:55:49 UTC] PHP Warning: PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\xampp\php\ext\php_imagick.dll (The specified module could not be found.
> ), C:\xampp\php\ext\php_php_imagick.dll.dll (The specified procedure could not be found.
> )) in Unknown on line 0
> 

I do have the file in the right location for XAMMP (C:\xampp\php\ext). 

Can anyone else reproduce this error and/or provide a solution? I can't use PHP 7.2 until this is solved (imagick works in PHP 7.1).

**Comment by narian** [comment] 2018-01-12 06:31
Exactly same thing happening

**Comment by Danack** [comment] 2018-01-12 11:08
It's telling you which files it's trying to load:

> tried: 
> C:\xampp\php\ext\imagick (The specified module could not be found.), 
> C:\xampp\php\ext\php_imagick.dll (The specified procedure could not be found.)

So it's trying the wrong file first and then allegedly the correct file.

> I do have the file in the right location for XAMMP (C:\xampp\php\ext).

With the older form it trying:

> tried: 
> C:\xampp\php\ext\php_imagick.dll (The specified module could not be found.), 
> C:\xampp\php\ext\php_php_imagick.dll.dll

It's trying the correct filename first, and then the wrong file name.

I'm pretty sure this will either be a permissions issue, or some other issue local to your machine, rather than something caused by the change in dll loading.

**Comment by tmb-github** [comment] 2018-01-12 15:04
No, I've used php_imagick.dll in every version of PHP in XAMPP for Windows since PHP 5.6, and it's worked consistently. I've never had this problem before. It worked on PHP 7.1.X without any issue. There are no permission conflicts or restrictions.

To prove this, I performed a little test:

One of the standard PHP extensions is php_bz2.dll. In my PHP.INI file, it's referenced like this:

`extension=bz2`

There are no error messages in the PHP error log file for it. So I changed the PHP.INI line to this:

`extension=bz2XXX`

...and put the php_imagick.dll declaration below it, like this:

`extension=bz2XXX`
`extension=imagick`

The result is the same error message as for imagick...here's the log file:

> [12-Jan-2018 14:48:12 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'bz2XXX' (tried: C:\xampp\php\ext\bz2XXX (The specified module could not be found.
> ), C:\xampp\php\ext\php_bz2XXX.dll (The specified module could not be found.
> )) in Unknown on line 0
> 
> [12-Jan-2018 14:48:12 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\xampp\php\ext\imagick (The specified module could not be found.
> ), C:\xampp\php\ext\php_imagick.dll (The specified procedure could not be found.
> )) in Unknown on line 0
> 

Then I removed the "XXX" from the end of the bz2 extension declaration in the PHP.INI file, like this:

`extension=bz2`
`extension=imagick`

...and the log file only shows that imagick cannot be loaded; php_bz2.dll is loaded just fine:

> [12-Jan-2018 14:52:00 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick' (tried: C:\xampp\php\ext\imagick (The specified module could not be found.
> ), C:\xampp\php\ext\php_imagick.dll (The specified procedure could not be found.
> )) in Unknown on line 0
> 

Both php_bz2.dll and php_imagick.dll are in the very same folder.

So...what's going on? Something's wrong with php_imagick.dll and the PHP 7.2.X distributions (the problem exists for 7.2.0 and 7.2.1).

(Also notice that the user "narian" above has experienced the same problem.)

**Comment by narian** [comment] 2018-01-15 06:10
@Danack Can your provide versions of ImageMagick and php_imagick that works with PHP7.2 on Windows? Because I thinks, it's only a Windows (or latest xampp) issue, I've tried to run imagick on Debian 9 on PHP7.2 and it works perfectly. Thanks!

**Comment by mvorisek** [comment] 2018-01-24 22:45
I confirm this issue on Windows.

It seems there is some problem with CORE_RL_*.dll files.

When I copy these files to php binary dir or put them in PATH:
a) with PHP 7.1 it works
b) with PHP 7.2 it fails with the misleading message above (but the php_imagick.dll is located sucessfully)

note: tested with http://windows.php.net/downloads/pecl/releases/imagick/3.4.3/php_imagick-3.4.3-7.1-nts-vc14-x64.zip

Can someone with deeper understanding of the PHP extensions ecosystem loop more deeper into this?

**Comment by Simbiat** [comment] 2018-01-30 17:59
Confirm the issue as well. And I wanted to move to it from GD =(

**Comment by odysseuscm** [comment] 2018-02-01 12:26
I also confirm this issue on Windows with PHP 7.2.x

**Comment by Simbiat** [comment] 2018-02-01 17:28
Strange, I tried that as well, but did not work for me. I am now using 7.2.2 from https://www.apachelounge.com/viewtopic.php?t=6359 and what fixed this for me is using ImageMagick ImageMagick 6.9.9-30 Q16 x64

**Comment by mvorisek** [comment] 2018-02-01 17:32
I confirm that the snapshot version for PHP 7.2 is working. When should we expect an official stable release?

**Comment by weltling** [comment] 2018-02-01 19:45
Hi,

the snapshot as linked is #219 requires ImageMagick 7.x as provided under http://windows.php.net/downloads/pecl/deps/ . It might be ok with a subsequent ImageMagick 7.x series, though tested and linked with the exact 7.0.7-11 as under the link. Note also, I've no idea how the official ImageMagick releases are built. The compiler has to match, thus for PHP 7.2 it's vc15. Please also use the official windows.php.net binaries for the tests.

For PHP 7.2, the intention was to use ImageMagick 7 having improvements and better security, for the imagick builds targeting lower PHP version, ImageMagick 6 still supporting security but being legacy as provided in the deps link has to be used. Be sure the corresponding DLLs are preceding any others on the `%PATH%`.

To mention, the bug https://bugs.php.net/bug.php?id=75890 has nothing to do with imagick, but is a codepage issue. 

Thanks.

**Comment by Jan-E** [comment] 2018-02-02 05:15
> Note also, I've no idea how the official ImageMagick releases are built. The compiler has to match, thus for PHP 7.2 it's vc15.

The official ImageMagick 6.x and 7.x releases have DLL's that call MSVCR120.dll, so they are all built with VC12. Ergo, the compilers do not match with any PHP version. You are lucky if it works, but don't be surprised if you get issues when you are mixing VC runtimes.

If anybody really wants to build php_imagick.dll for PHP 7.2 with ImageMagick 7.x, the following is needed:

1. Build your own ImageMagick binaries with VC15. Ref: http://imagemagick.org/script/install-source.php
2. Apply PR https://github.com/mkoppanen/imagick/pull/219
3. Build php_imagick.dll with VC15. Ref: https://github.com/Microsoft/php-sdk-binary-tools

**Comment by Jan-E** [comment] 2018-02-02 05:36
The official ImageMagick releases are apparently built using Appveyor. See https://github.com/ImageMagick/ImageMagick-Windows/blob/master/appveyor.yml which confirms that they are using Visual Studio 2013 aka VC12.

**Comment by weltling** [comment] 2018-02-03 18:06
Thanks for checking, @Jan-E. Ditto.

Thanks.

**Comment by Code4Dopes** [comment] 2018-02-17 02:32
Throwing my confirmation into the ring:

Apache 2.4,29/PHP7.2.2 on a Win7 machine (VC14 ThreadSafe).

php_imagick-3.4.3-7.1-ts-vc14-x64  --> No Joy
php_imagick-3.4.3-7.2-ts-vc15-x64  --> SheBang! :o)

I dunno if the vc15 is 100% accurate but I do NOT have 
the vc15 redistributable installed (only vc14/vs2015). Also.
I got phpinfo-imagick to confirm working and then used a few
web pages we have, but did not check every nook & cranny.

Thank you odysseuscm!

**Comment by boan2010** [comment] 2018-02-19 12:17
Where did you find php_imagick-3.4.3-7.2-ts-vc15-x64?

It's not in the list on this date:
https://pecl.php.net/package/imagick

**Comment by odysseuscm** [comment] 2018-02-19 12:39
@boan2010 https://github.com/mkoppanen/imagick/issues/224#issuecomment-362251137

**Comment by chfabbro** [comment] 2018-02-22 01:06
For those of you like me who have never installed ImageMagick on Windows with PHP, let alone for PHP 7.2, I found this article very useful:
[Install the ImageMagick PHP extension in Windows](https://mlocati.github.io/articles/php-windows-imagick.html)

The table here only goes up to PHP 7.1, so I also confirm that using these builds worked for me on PHP 7.2.2/Windows 10 (thread-safe version):
- ImageMagick-7.0.7-11-vc15-x64.zip
- php_imagick-3.4.3-7.2-ts-vc15-x64.zip

The workflow seems really clunky to me, but I did exactly as instructed:
- Extract from php_imagick-….zip to the ext directory the php_imagick.dll file of your PHP installation
- Extract from ImageMagick-….zip to the root PHP directory (where php.exe resides) the DLL files that start with (and there are a TON):
  `CORE_RL_`
  `IM_MOD_RL_`
- Add this line to your php.ini file
  `extension=imagick`

And then to run a simple test (should output a 1):
`php -r "print(class_exists('imagick'));"`

If anyone knows a more elegant installation solution, please let me know 😸

**Comment by Jan-E** [comment] 2018-02-22 02:18
Newer ImageMagick-6.9 binaries can be found here:
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/build/ImageMagick-ImageMagick-Windows-6-VS2017.62
Check the artefacts of each job to download the binaries.
@weltling The VC14 artefacts are similar like the ones at http://windows.php.net/downloads/pecl/deps/
Maybe it is time to use Appveyor to build the deps.

For the others: all my PHP builds at https://www.apachelounge.com/viewtopic.php?t=6359 are built with ImageMagick 6.9.9-35 Q16 x64 2018-02-02

**Comment by Jan-E** [comment] 2018-02-22 10:02
> @weltling The VC14 artefacts are similar like the ones at http://windows.php.net/downloads/pecl/deps/

@weltling I changed the artefact filenames into names like ImageMagick-6.9.9-35-vc15-x86.zip and added the LICENSE:
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/build/ImageMagick-ImageMagick-Windows-6-VS2017.106

There is a huge ffmpeg.exe in the bin directory, which makes the zipfile bigger than strictly necessary.

**Comment by tmb-github** [comment] 2018-03-14 00:51
Following the tips provided earlier in the thread, I succeeded in getting imagick to load in PHP 7.2 on my Windows XAMPP when I went here:

https://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/

...and downloaded & installed this x86 "snapshot" file set:

11/23/2017  4:51 PM      9072708 php_imagick-3.4.3-7.2-ts-vc15-x86.zip

...on top of the current 3.4.3 set at https://pecl.php.net/package/imagick (thus, overwriting some of its files).

I hope whoever is maintaining the pecl repos will update the DLLs accordingly. Thanks for everyone who posted and help solve this problem for me. I hope it will help others solve similar problems.

**Comment by Zigito** [comment] 2018-04-07 00:42
After 3 hours of installing, un-installing and re-installing I was finally able to make it work. Basically, it's important to check your phpinfo() for your architecture and compiler versions: mine was x86 and MSVC15. 

Based on this you want to head to [imagemagick](https://www.imagemagick.org/script/download.php#windows) and download the appropriate executable
ImageMagick-7.0.7-28-Q16-x86-dll.exe

After installing run "magick -version" in the command prompt to verify installation. You should see version information.

Then head  [here](https://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/ ) and download php_imagick-3.4.3-7.2-ts-vc15-x86.zip . Unzip and copy the php_imagick.dll to the path c:\xampp\php\ext

Edit php.ini and add  the following line under Dynamic Extensions where the other extensions are loaded
extension=php_imagick.dll

Head  [here](https://windows.php.net/downloads/pecl/deps/) and download ImageMagick-7.0.7-11-vc15-x86.zip . Unzip and copy all files with prefixes CORE_* and IM_MOD_* , and add them to c:\xampp\apache\bin. Also add  c:\xampp\apache\bin to your .

You will need to add the bin directory of Apache (C:\xampp\apache\bin) to the PATH environment variable of Windows.

**Comment by fridzema** [comment] 2018-04-10 10:12
Anyone dealing with this problem on osx?
I am running 10.13.3 with php 7.2.4 and can't get it to work anymore :(

**Comment by mlocati** [comment] 2018-04-10 14:12
> The table here only goes up to PHP 7.1

I updated [the imagick install instructions](https://mlocati.github.io/articles/php-windows-imagick.html): it now includes instructions about how to install ImageMagick on Windows with PHP 7.2

**Comment by mlocati** [comment] 2018-04-10 14:16
> If anyone knows a more elegant installation solution, please let me know

@chfabbro If you don't want all those DLL files in your PHP directory, you can have them in any directory in your PATH (from my [article](https://mlocati.github.io/articles/php-windows-imagick.html): "or to a directory present in your PATH environment variable")

**Comment by patrickbussmann** [comment] 2018-06-04 10:51
@mlocati solution is as cool as possible 🎉 
Now upgrades are very quick and easy and installing extensions, too.
Thank you very much.

**Comment by LG0012** [comment] 2018-06-20 13:29
Still not working: http://prntscr.com/jx6ara

PHP: 7.1.16
TS: Enabled
x86

**Comment by mlocati** [comment] 2018-06-20 14:44
@LG0012 I just tried to install imagick both on PHP 7.1 and 7.2 (thread-safe, x86), without any problems:

```powershell
PS C:\test> Install-Php -Version 7.2 -Architecture x86 -ThreadSafe $true -Path C:\test\7.2 -TimeZone Europe/Rome -InitialPhpIni Development
PS C:\test> Install-PhpExtension -Extension imagick -MinimumStability snapshot -Path C:\test\7.2
PS C:\test> C:\test\7.2\php.exe -r '$image = new Imagick(); $image->newImage(1, 1, new ImagickPixel(\"#ffffff\")); $image->setImageFormat(\"png\"); $pngData = $image->getImagesBlob(); echo strpos($pngData, \"\x89PNG\r\n\x1a\n\") === 0 ? \"Ok\" : \"Failed\";'
Ok
PS C:\test> Install-Php -Version 7.1 -Architecture x86 -ThreadSafe $true -Path C:\test\7.1 -TimeZone Europe/Rome -InitialPhpIni Development
PS C:\test> Install-PhpExtension -Extension imagick -Path C:\test\7.1
PS C:\test> C:\test\7.1\php.exe -r '$image = new Imagick(); $image->newImage(1, 1, new ImagickPixel(\"#ffffff\")); $image->setImageFormat(\"png\"); $pngData = $image->getImagesBlob(); echo strpos($pngData, \"\x89PNG\r\n\x1a\n\") === 0 ? \"Ok\" : \"Failed\";'
Ok
```

**Comment by mlocati** [comment] 2018-06-20 14:48
PS:
```powershell
PS C:\test> Get-Php -Path C:\test\7.2
Folder         : C:\test\7.2
ExecutablePath : C:\test\7.2\php.exe
ExtensionsPath : C:\test\7.2\ext
Version        : 7.2.7
RC             :
FullVersion    : 7.2.7
DisplayName    : PHP 7.2.7 x86 (32-bit) Thread-Safe
Architecture   : x86
ThreadSafe     : True
VCVersion      : 15

PS C:\test> Get-PhpExtension -Path C:\test\7.2 | Where-Object { $_.Name -eq 'imagick' }
Type     : Php
State    : Enabled
Name     : imagick
Handle   : imagick
Version  : @PACKAGE_VERSION@
Filename : C:\test\7.2\ext\php_imagick.dll

PS C:\test> Get-Php -Path C:\test\7.1
Folder         : C:\test\7.1
ExecutablePath : C:\test\7.1\php.exe
ExtensionsPath : C:\test\7.1\ext
Version        : 7.1.18
RC             :
FullVersion    : 7.1.18
DisplayName    : PHP 7.1.18 x86 (32-bit) Thread-Safe
Architecture   : x86
ThreadSafe     : True
VCVersion      : 14

PS C:\test> Get-PhpExtension -Path C:\test\7.1 | Where-Object { $_.Name -eq 'imagick' }
Type     : Php
State    : Enabled
Name     : imagick
Handle   : imagick
Version  : 3.4.3
Filename : C:\test\7.1\ext\php_imagick.dll
```

**Comment by LG0012** [comment] 2018-06-20 14:49
Then I have no idea what its going on. We are using Xampp right now, maybe because of that?

**Comment by LG0012** [comment] 2018-06-20 14:50
Ok, so your php version is different, I will try to update that.

**Comment by mlocati** [comment] 2018-06-20 14:53
I don't think that the problem is the PHP version (and I don't know what's going wrong):

```powershell
PS C:\test> Install-Php -Version 7.1.16 -Architecture x86 -ThreadSafe $true -Path C:\test\7.1.16 -TimeZone Europe/Rome -InitialPhpIni Development
PS C:\test> Install-PhpExtension -Extension imagick -Path C:\test\7.1.16
PS C:\test> C:\test\7.1.16\php.exe -r '$image = new Imagick(); $image->newImage(1, 1, new ImagickPixel(\"#ffffff\")); $image->setImageFormat(\"png\"); $pngData = $image->getImagesBlob(); echo strpos($pngData, \"\x89PNG\r\n\x1a\n\") === 0 ? \"Ok\" : \"Failed\";'
Ok
```

**Comment by LG0012** [comment] 2018-06-20 14:54
We are using this package in our laravel project - "bacon/bacon-qr-code". Maybe something wrong with that one, I will take a look at this, and will came back with the response.

**Comment by Jan-E** [comment] 2018-06-20 15:01
"The specified module could not be found" is often a sign that a dependency of the module is missing. Make sure, that at least the correct (x86/x64, vc-version) core_rl_wand_.dll and core_rl_magick_.dll are first in the path or in the directory with php.exe.

**Comment by LG0012** [comment] 2018-06-20 15:07
Inside ImageMagick zip folder, I see 3 folders: bin, include, lib.

Regarding the guides, everybody is saying that - from ImageMagick zip folder you only have to copy all core_rl and im_mod_rl files into apache/bin folder. Thats what I did and the question is, what about other folders or files?

**Comment by mlocati** [comment] 2018-06-20 15:07
> Make sure, that at least the correct (x86/x64, vc-version) core_rl_wand_.dll and core_rl_magick_.dll are first in the path or in the directory with php.exe.

There are more dll used by the imagick extension:

![immagine](https://user-images.githubusercontent.com/928116/41667094-6e36a500-74ac-11e8-9d3a-b50b981e668c.png)

**Comment by mlocati** [comment] 2018-06-20 15:09
@LG0012 try following [my imagick install instructions](https://mlocati.github.io/articles/php-windows-imagick.html) (or use my [PhpManager](https://github.com/mlocati/powershell-phpmanager) powershell module - like I did in the above examples of mine).

**Comment by Jan-E** [comment] 2018-06-20 15:17
@LG0012 
> Regarding the guides, everybody is saying that - from ImageMagick zip folder you only have to copy all core_rl and im_mod_rl files into apache/bin folder.

Chances are high that PHP cannot find the dll's in the apache/bin folder. A better place is the php folder.

**Comment by Jan-E** [comment] 2018-06-20 16:07
@mlocati 
> There are more dll used by the imagick extension

I am very well aware of that, because I am building ImageMagick 6 on AppVeyor myself for Visual Studio 2015 and 2017: https://github.com/Jan-E/ImageMagick-Windows/branches

ImageMagick is smart enough to look for and find the IM_\*.dll's in `C:\Program Files\ImageMagick\modules\coders` (x64) or `C:\Program Files (x86)\ImageMagick\modules\coders` (x86), even if those folders are not in your path. So the IM_*.dll files do not have to be in the PHP folder if you have ImageMagick x86 and x64 installed on your system.

**Comment by 4532066** [comment] 2018-07-07 11:50
I'm running Windows 10 64 bit and after a couple of hours of messing about I got this to work in the end by the following:

1. Installing IM from [(https://www.imagemagick.org/script/download.php#windows)](https://www.imagemagick.org/script/download.php#windows)
Win64 dynamic at 8 bits-per-pixel component (ImageMagick-7.0.8-5-Q8-x64-dll.exe)

2. Editing c:\xampp\php\php.ini and adding extension=php_imagick.dll to this section:

;;;;;;;;;;;;;;;;;;;;;;
; Dynamic Extensions ;
;;;;;;;;;;;;;;;;;;;;;;

3. Going to [https://mlocati.github.io/articles/php-windows-imagick.html](https://mlocati.github.io/articles/php-windows-imagick.html)

Running these from cmd window:

**php -i|find "PHP Version"**
PHP Version => 7.2.5

**php -i|find "Thread Safety"**
Thread Safety => enabled

**php -i|find "Architecture"**
Architecture => x86

From there:

- Downloaded Extension: php_imagick-3.4.3-7.2-ts-vc15-x86.zip
- Unzipped the Extension and copied `php_imagick.dll` to `C:\xampp\php\ext`

- Downloaded ImageMagick ImageMagick-7.0.7-11-vc15-x86
- Unzipped that, copied *.DLL from the bin folder in there, excluding `ImageMagickObject.dll` to `C:\xampp\apache\bin`

4. Restarted Apache

I didn't need to add manually anything to the path in Windows Environment variables.

Then phpinfo(); confirmed ImageMagick was installed.

**Comment by mlocati** [comment] 2018-07-07 12:22
With https://github.com/mlocati/powershell-phpmanager you can do everything with just this powershell command:

```powerwhell
Install-PhpExtension imagick -MinimumStability snapshot
```

**Comment by abinhho** [comment] 2018-12-05 11:10
I got same thing,
When I check phpinfo() in browser, Imagick shown bit in terminal, I just run `php -v` and got error

This is in browser:
```
imagick module | enabled
-- | --
imagick module version | 3.4.3
imagick classes | Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version | ImageMagick 6.9.3-7 Q16 x86 2016-03-27 http://www.imagemagick.org
Imagick using ImageMagick library version | ImageMagick 6.9.3-7 Q16 x86 2016-03-27 http://www.imagemagick.org
ImageMagick copyright | Copyright (C) 1999-2015 ImageMagick Studio LLC
ImageMagick release date | 2016-03-27
ImageMagick number of supported formats: | 0
ImageMagick supported formats | no value


```

This is result in command line
```
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp7.1\php\ext\php_imagick.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp7.1\php\ext\php_imagick.dll' - The specified module could not be found.
 in Unknown on line 0
PHP 7.1.24 (cli) (built: Nov  8 2018 05:28:30) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

Im sure I push php_imagick.dll in `ext/`.

Any help?

**Comment by mlocati** [comment] 2018-12-05 11:14
@abinhho it's not enough to have the `php_imagick.dll` file (this is the `imagick` PHP extension): you also need the `ImageMagick` DLL files.
To install them, see https://mlocati.github.io/articles/php-windows-imagick.html (or https://github.com/mlocati/powershell-phpmanager)

**Comment by abinhho** [comment] 2018-12-06 01:55
@mlocati
I also installed both `ImageMagick ` and `php_imagick.dll` but it's not right version. After used your ways, It's worked for me. 

Many thanks !!! 🥇

**Comment by garyrowswell** [comment] 2018-12-11 12:32
@mlocati very useful. Will you be updating for PHP 7.3 now out as stable?

**Comment by mlocati** [comment] 2018-12-11 13:53
@garyrowswell That's not something under my control.

I simply use the compiled DLLs found in the [releases](https://windows.php.net/downloads/pecl/releases/imagick/) or [snapshot](https://windows.php.net/downloads/pecl/snaps/imagick/) PECL builds, but there are no builds for PHP 7.3. 
Maybe @Danack or @mkoppanen can do something about it...

**Comment by Jan-E** [comment] 2018-12-11 14:22
@weltling must be able to trigger snapshot builds for PHP 7.3

**Comment by mlocati** [comment] 2018-12-11 14:49
Any reason why there's only a snapshot build of imagick.dll for PHP 7.2?

**Comment by weltling** [comment] 2018-12-11 14:53
Thanks for the ping. The snapshot is now running, please check same location in a couple of hours.

@mlocati it's triggered manually. Whenever you need some, please ping :)

Thanks.

**Comment by mlocati** [comment] 2018-12-11 14:57
@weltling I'm wondering why there's a [snapshot build for PHP 7.2](https://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/), but [release builds for PHP 7.1-](https://windows.php.net/downloads/pecl/releases/imagick/3.4.3/)...

**Comment by weltling** [comment] 2018-12-11 15:05
@mlocati AFAIR that one was done specifically to cover a PR with 7.2 related fixes. In general, arbittary snapshots are triggered manually. Except, when a new PHP version is in pre cycle, usually regular PECL releases are built also against some pre PHP version. For automatic builds it's essential something to be release on PECL, as the build bot only fetches tarballs from there.

Thanks.

**Comment by mlocati** [comment] 2018-12-11 15:14
> @mlocati very useful. Will you be updating for PHP 7.3 now out as stable?

@garyrowswell I updated https://mlocati.github.io/articles/php-windows-imagick.html so that it now includes PHP 7.3

[PhpManager](https://github.com/mlocati/powershell-phpmanager) should be able to install imagick by using the `snapshot` flag:

```PowerShell
Install-PhpExtension -Extension imagick -MinimumStability snapshot -Path C:\Path\To\PHP7.3
```

**Comment by garyrowswell** [comment] 2018-12-11 16:36
@mlocati Excellent. The ImageMagick website lists 7.0.8-16 as latest release would that install the files necessary for the imagick php extension or can the pecl dep for imagemagick be updated to latest version as well?

**Comment by mlocati** [comment] 2018-12-11 16:58
I absolutely don't know... just try it :wink:

**Comment by garyrowswell** [comment] 2018-12-12 10:36
@mlocati Using the latest from imagemagick.org does work, but php issues a warning. @weltling is there any chance the imagick extension can be recompiled for this latest imagemagick version? (if that's the right thing to ask)

> Imagick was compiled against ImageMagick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly

**Comment by chfabbro** [comment] 2018-12-12 19:37
@garyrowswell I see new snapshot builds posted yesterday: https://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/ 

Perhaps one of these was compiled for the new version?

**Comment by weltling** [comment] 2018-12-15 20:38
@garyrowswell no plans for dependency upgrades in the near future, at least this year. Could be reconsidered, if there are some hard weight issues with the current version.

Thanks.

**Comment by AnrDaemon** [comment] 2019-02-14 12:43
Can somebody please push a button to release compiled Windows binaries on PECL website proper?

**Comment by Jan-E** [comment] 2019-02-14 13:23
@weltling The 7.2 & 7.3 versions at https://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/ aren't linked at https://pecl.php.net/package/imagick/3.4.3/windows
Can you copy them to https://windows.php.net/downloads/pecl/releases/imagick/3.4.3/ ?

**Comment by mialdi98** [comment] 2019-03-12 07:40
> For those of you like me who have never installed ImageMagick on Windows with PHP, let alone for PHP 7.2, I found this article very useful:
> [Install the ImageMagick PHP extension in Windows](https://mlocati.github.io/articles/php-windows-imagick.html)
> 
> The table here only goes up to PHP 7.1, so I also confirm that using these builds worked for me on PHP 7.2.2/Windows 10 (thread-safe version):
> 
> * ImageMagick-7.0.7-11-vc15-x64.zip
> * php_imagick-3.4.3-7.2-ts-vc15-x64.zip
> 
> The workflow seems really clunky to me, but I did exactly as instructed:
> 
> * Extract from php_imagick-….zip to the ext directory the php_imagick.dll file of your PHP installation
> * Extract from ImageMagick-….zip to the root PHP directory (where php.exe resides) the DLL files that start with (and there are a TON):
>   `CORE_RL_`
>   `IM_MOD_RL_`
> * Add this line to your php.ini file
>   `extension=imagick`
> 
> And then to run a simple test (should output a 1):
> `php -r "print(class_exists('imagick'));"`
> 
> If anyone knows a more elegant installation solution, please let me know 😸

works for 7.1 fine too! (win10 x32(x86) php 7.1 XAMPP 3.2.2)
but with small add u need to add this bunch of dlls in Apache\bin too.

**Comment by jerry-cbn** [comment] 2019-04-17 07:13
> into the PHP root directory (where you have php.exe), or to a directory in your PATH variable


Be careful !! The PHP root directory MUST BE known in the PATH variable.
And it's not necessarily the case (it wasn't for me, I using WAMP).
After added my PHP root directory to my PATH variable, it works like a charm.

**Comment by AnrDaemon** [comment] 2019-04-17 09:43
> The PHP root directory MUST BE known in the PATH variable. 

That's absolutely not true.
Enough that you have a proper association to run `*.php` files.

**Comment by schmidtl4** [comment] 2019-05-02 13:38
@mlocati  - Awesome PHPManager power shell module.  Fixed my imagick installation challenges and will be my goto module for managing PHP installation.  Beautiful!  Thanks.

**Comment by Danack** [comment] 2019-05-03 15:21
I'm going to close this issue as I don't think there's anything that needs to be done within this repo to resolve any problems people are having.

If anyone wants to step up and be the 'official windows Imagick maintainer' to deal with this sort of thing, that would be awesome.

**Closed by Danack** 2019-05-03 15:21 UTC

**Comment by patieru12** [comment] 2019-10-02 11:17
> 
> 
> I also confirm this issue on Windows with PHP 7.2.x
> 
> Update: got it to work with this snapshot http://windows.php.net/downloads/pecl/snaps/imagick/3.4.3/
> using only the php_imagick.dll from the archive and Imagick 7.0.7-22

Works Fine for me great thanks

**Comment by steinhaug** [comment] 2019-11-09 23:34
Same problem here, but reading all the comments here I found the sollution thankfully!

The missing information is that the CORE_RL_* and IM_MOD_RL_* files should **NOT BE COPIED INTO EXTENSIONS DIRECTORY**, however into your main PHP directory. So in my case where php is installed at c:\php the steps would be:

1. copy "php_imagick.dll" into c:\php\ext
2. add "extension=imagick" into php.ini
3. copy "CORE_RL_*" into c:\php
4. copy "FILTER_*" into c:\php
5. copy "IM_MOD_RL_*" into c:\php

Restart Apache and done!

**Comment by mlocati** [comment] 2019-11-10 00:08
@steinhaug those instruction are already available at the [page I linked above](https://github.com/Imagick/imagick/issues/224#issuecomment-380113583), that is https://mlocati.github.io/articles/php-windows-imagick.html

**Comment by imomer** [comment] 2021-04-18 21:24
How to install it on Windows 10 x64, Apache2.4, PHP v7.4. I have tried all the above methods. Not a single one worked for me 😢

**Comment by mlocati** [comment] 2021-04-18 21:34
@imomer you can use https://mlocati.github.io/articles/php-windows-imagick.html or https://github.com/mlocati/powershell-phpmanager

**Comment by imomer** [comment] 2021-04-25 06:59
> @imomer you can use https://mlocati.github.io/articles/php-windows-imagick.html or https://github.com/mlocati/powershell-phpmanager

Worked for me... Thanks Mate 👍

**Comment by tmb-github** [comment] 2021-04-25 14:18
Has anyone worked out how to compile an imagick extension for PHP 8? I need it for my lives sites as well as my Windows-based localhost.

**Comment by Jan-E** [comment] 2021-04-25 21:27
Inside the zips at https://www.apachelounge.com/viewtopic.php?t=6359
With the dependent DLL's here:
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/builds/36477084/job/qk4mql7svrxsjor7/artifacts (x64)
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/builds/36477084/job/8vmap42odmfqp713/artifacts (x86)

**Comment by dekker-m** [comment] 2021-09-01 13:11
What fixed the issue for me was to install the Visual C++ Redistributable for Visual Studio 2015 package. I think I have been struggeling with the same issue multiple times in the past (and I think I might not be the only one).

**Comment by Allexim** [comment] 2024-03-03 08:52
imagick must be loaded before gd!
10-imagick.ini
20-gd.ini

**Comment by MaferNovastratics16** [comment] 2024-07-23 03:08
> Same problem here, but reading all the comments here I found the sollution thankfully!
> 
> The missing information is that the CORE_RL_* and IM_MOD_RL_* files should **NOT BE COPIED INTO EXTENSIONS DIRECTORY**, however into your main PHP directory. So in my case where php is installed at c:\php the steps would be:
> 
> 1. copy "php_imagick.dll" into c:\php\ext
> 2. add "extension=imagick" into php.ini
> 3. copy "CORE_RL_*" into c:\php
> 4. copy "FILTER_*" into c:\php
> 5. copy "IM_MOD_RL_*" into c:\php
> 
> Restart Apache and done!
@steinhaug
This work for me!! Thank you very much, I just spent two hours making work Imagick
