### ISSUE TITLE
Animated gif issues PHP 5.3, Ubuntu 12.04, Imagick 3.1

### ISSUE THREAD

**Issue by casperwilkes** [mkoppanen/imagick#20] opened 2014-02-14 02:32 UTC
Hello, I've been having problem with animated gifs on Ubuntu. I have Imagemagick and Imagick installed on both Windows 7 and Ubuntu 12.04. In Windows, everything works as expected, but in Ubuntu, it seems that only the first image of a coalesced gif is being saved. A problem with writeImages() maybe? 

*Ubuntu:
-Distributor ID:	Ubuntu
-Description:	Ubuntu 12.04.4 LTS
-Release:	12.04
-Codename:	precise

*PHP:
-PHP Version: 5.3.10-1ubuntu3.9
-PHP API:	20090626
-PHP Extension Build: API20090626,NTS

*Imagick:
-imagick module version:	3.1.0RC1

*ImageMagick:
-Version: ImageMagick 6.8.7-0 2013-10-11 Q16 http://www.imagemagick.org
-Copyright: Copyright (C) 1999-2013 ImageMagick Studio LLC
-Features: DPC OpenMP
-Delegates: zlib

Here is the function that was giving me problems. Again, it works in Windows, but not Linux.

```php
<?php
function resize($file_src) {
    try {
        set_time_limit(180);
        $image = new Imagick($file_src);
        $destination = dirname(__FILE__) . DS . 'images' . DS . basename($file_src);
        $images = $image->coalesceImages();
        $size_w = 250;
        $size_h = 250;

        foreach ($images as $frame) {
            $frame->thumbnailImage($size_w, $size_h);
        }

        $images->writeImages($destination, true);
    } catch (Exception $e) {
        echo $e->getMessage();
    }
}
?>
```

This is the command line version of the same function:

```php
<?php
function resize_cmd($file_src) {
    set_time_limit(180);
    $destination = dirname(__FILE__) . DS . 'images' . DS . basename($file_src);
    $w = 250;
    $h = 250;

    exec("convert {$file_src} -coalesce -resize {$h}x{$w} {$destination}", $output);
    if (!empty($output)) {
        echo $output;
    }
}
?>
```

The second function "resize_cmd()" works without a problem.

**Comment by tmli3b3rm4n** [comment] 2015-02-10 16:19
I still can't get writeImages() to work properly on : ImageMagick 6.7.8-9 2014-05-12 Q16.  It was working in production and now it's shot to hell.  Still working to find issue.

**Comment by Danack** [comment] 2015-02-10 17:27
@tmli3b3rm4n Can you list what version of giflib you're using? or the appropriate library if not giflib.

Also, please can you try converting the image to an animated gif with the ImageMagick convert command.

I recently added an animated gif test to the Imagick test suites and it works fine on my machine, but fails on Travis - so I suspect it is a library issue, but haven't been able to investigate it yet.

**Comment by tmli3b3rm4n** [comment] 2015-02-10 21:48
This is exactly what's happening here.  It works locally but fails on qa servers.   Let me get you the information you're asked for.

**Comment by tmli3b3rm4n** [comment] 2015-02-10 22:05
Name        : giflib
Arch        : x86_64
Version     : 4.1.6
Release     : 3.1.6.amzn1

**Comment by Danack** [comment] 2015-02-10 22:41
Do you have a vagrant script box that you can share to recreate the issue? If not I guess I'll try with the puphet one which apparently is "Ubuntu Precise 12.04 LTS x64"

For reference, I'm on Centos 6.4 and the versions of giflib I'm apparently using are:
giflib.x86_64         4.1.6-3.1.el6     @base                                   
giflib-devel.x86_64   4.1.6-3.1.el6     @base

And everything works for me :^)

**Comment by Danack** [comment] 2015-02-11 03:15
Just to add, apparently Travis is pulling in ImageMagick from here http://packages.ubuntu.com/precise/imagemagick - so I ought to test with that also.

**Comment by tmli3b3rm4n** [comment] 2015-02-11 13:30
I ended just stripping all the writeImages() out using Gaufrette and writing straight to s3 with getImagesBlob().  I don't know what happened to writeImages() but writing was failing on gif's.

**Comment by Danack** [comment] 2015-02-12 19:04
Actually @tmli3b3rm4n I can't reproduce this on Ubuntu, and it's not an issue on Travis - I thought it was but it was just that the image generation function was failing.

Can you check to see if ImageMagick was compiled with OpenMP enabled? If so that may be the issue so please try either recompiling ImageMagick or set:

    Imagick::setResourceLimit(\Imagick::RESOURCETYPE_THREAD, 1);

To disable OpenMP and let me know if that fixes the issue?

**Comment by Danack** [comment] 2015-02-13 19:37
This is really very similar to https://bugs.php.net/bug.php?id=61879

Please can you confirm that you're using at least version 3.1.0RC2 ?

**Comment by tmli3b3rm4n** [comment] 2015-02-13 21:43
I'll check and get back to you.

**Comment by Danack** [comment] 2015-02-18 15:32
I'm going to close this again. There was a known issue that has been fixed. If you find any evidence it's a separate issue, please feel free to add more info.

**Closed by Danack** 2015-02-18 15:32 UTC

**Comment by tmli3b3rm4n** [comment] 2015-02-23 21:55
Will do.
