### ISSUE TITLE
BUG - Saving to TIFF format lossless compressed broke the image

### ISSUE THREAD

**Issue by Yivan** [mkoppanen/imagick#178] opened 2016-10-07 11:56 UTC
Hello,

Saving image in TIFF format doesn't work, as the resulting image has the color broken (near black and white).

Code:
```
$sourceFile = "/tmp/test.png"; // any source format will do
$tmpFile = "/tmp/test-" . uniqid() . ".tif";
$i = new Imagick();
$i->readImage($sourceFile);
$i->setCompression(\Imagick::COMPRESSION_LZW);
$i->writeImage("tiff:" . $tmpFile);
```

I tried the following lossless compression method, each one with all availables \Imagick::COLORSPACE_{name}:
COMPRESSION_FAX
COMPRESSION_GROUP4
COMPRESSION_LZW
COMPRESSION_ZIP
And they all break the image.

So actually it is not possible to save as TIFF lossless in a reasonable size as uncompressed files are huge for TIFF.

Environement where it has been reproducted (i didn't try other):
```
imagick module version: 3.4.2
Imagick using ImageMagick library version: ImageMagick 6.8.9-9 Q16 x86_64 2016-09-23
```
and same for this one wich is a stable jessie updated from official repo:
```
imagick module version: 3.2.0RC1
Imagick using ImageMagick library version: ImageMagick 6.8.9-9 Q16 x86_64 2016-09-23
```

Please, feel free to ask any needed information.

Thank you.

**Comment by Danack** [comment] 2016-10-07 12:10
Hi,

Please can you post an example of a broken image somewhere.

Also, this is likely to be a bug in the underlying ImageMagick library. Please can you try to reproduce the behaviour using ImageMagick's command line `convert` utility. If it is, then this will save a lot of time to be able to report it upstream.

cheers
Dan

**Comment by Yivan** [comment] 2016-10-07 19:29
Thanks for your fast answer Danack.
Here is an exemple, poor lena is no more so nice in tiff ; ) :
[lena-test.zip](https://github.com/mkoppanen/imagick/files/516968/lena-test.zip)
(zipped file with the original jpg and the converted tiff, by running the same code than in my first post)

I will try with convert on the same imagick library version, and will update this issue after.

**Comment by Yivan** [comment] 2016-10-07 19:56
Ok I just tested, on the same station used for the PHP test (a web server), by installing ImageImagick binary package form the official repository (https://packages.debian.org/jessie/imagemagick).
I run Debian Jessie, updated, only official repo.
I made in command line, root user:
```
apt-get install imagemagick
convert --version // output: Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-09-23
convert lena-test.jpg lena-test-binarylibcmd.tif
```
Here is the resulting image, there is no problem, all is ok:
[lena-test-binarylibcmd.zip](https://github.com/mkoppanen/imagick/files/517007/lena-test-binarylibcmd.zip)

It seems problem is imagick php. And the version I used for php is the official PHP of debian jessie repository (php is configured in module, not fastcgi) : https://packages.debian.org/jessie/php5-imagick
All the web server is based on stable jessie and up-to-date (apt-get clean && apt-get update), so it is really easy for you to repoduce the problem by just installing debian jessie from scratch with PHP module and running the script in my first post, with any jpg or png image as input.

Don't hesitate to ask more information if needed.
Thanks a lot.

**Comment by Danack** [comment] 2016-10-09 09:09
Hi @Yivan 

Sorry, I can't reproduce your issue.

Please can you run your PHP script through valgrind to see if there are any memory errors in the version of ImageMagick you are using, e.g. like:

```valgrind php test.php```

Also, please can you add the compress option to the ImagickMagick CLI test, to check with the compression set:

```convert -compress lzw lena-test.jpg lena-test-binarylibcmd.tif```


If those two don't reveal anything interesting, you may need to try agains a more up to date version of ImageMagick + Imagick. It's possible this is an issue that has been fixed since 6.8.9-9

cheers
Dan

**Comment by Yivan** [comment] 2016-10-09 18:29
Thanks!
How i was tired yes, i forgotten the compression option in command line binary.
So i have tested with:
`convert -compress lzw lena-test.jpg lena-test-binarylibcmd-lzw.tif`
And output is breaked exactly the same than by running php imagick. Same size output too.

So problem is not php extension, but directly imagickmagick library.
Here are zipped, the php script, valgrind output, and lena tiff with lzw using commend line binary.
[test-valgrind.zip](https://github.com/mkoppanen/imagick/files/518481/test-valgrind.zip)

I will try to test another version of imagickmagick so and keep posting result here. But as this bug impact the stable debian package, shouldn't it be patched for this version in anycase ?

**Comment by Danack** [comment] 2016-10-09 18:48
fyi I'm using ImageMagick 6.9.2-0 Q16

I'm suspect it's already fixed in the upstream package of ImageMagick, which is why I don't see it.

> as this bug impact the stable debian package, shouldn't it be patched for this version in anycase ?

If the Debian maintainers are able to pick out the precise commit that fixed this in ImageMagick, and apply it to their stable release, then it would be up to them to figure out whether to apply that to their stable package.

As you're able to reproduce the issue through the command line version of ImageMagick, I doubt there will be anything I can do to resolve this issue for you - so I'm going to close this for now. Feel free to ask for advice....it's just that the PHP Imagick library is a really thin wrapper, so it's not able to work around bugs like.

**Closed by Danack** 2016-10-09 18:48 UTC

**Comment by Yivan** [comment] 2016-10-09 19:30
Thanks Danack and yes the has to be closed so.

For information for records, i found a solution from here : https://www.reddit.com/r/imagemagick/comments/3tqhmx/tiff_compression_broken_on_debian_jessie/

So updating libtiff make tiff working.

I downloaded the stretch libtiff
and install it by doing as root user:

```
cd ~
wget http://ftp.fr.debian.org/debian/pool/main/t/tiff/libtiff5_4.0.6-2_amd64.deb
dpkg-deb -R libtiff5_4.0.6-2_amd64.deb ./libtiff
cp ./libtiff/usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4 /usr/lib/x86_64-linux-gnu/
rm /usr/lib/x86_64-linux-gnu/libtiff.so.5
ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5.2.4 /usr/lib/x86_64-linux-gnu/libtiff.so.5
```
