### ISSUE TITLE
Time for a new version ?

### ISSUE THREAD

**Issue by remicollet** [mkoppanen/imagick#183] opened 2016-11-03 11:25 UTC
Current versions / stability on https://pecl.php.net/package/imagick are a bit confusing...

* 3.4.3RC1 	stable 	2016-06-09
* 3.4.2 	beta 	2016-04-24
* 3.4.1 	stable 	2016-03-09

Perhaps time for a real 3.4.3 stable ?  (RC1 was released 5 months ago)

**Comment by dzuelke** [comment] 2016-11-24 01:03
Yes, @Danack, please release a 3.4.3 final version. PHP 7.1.0 will be released in a week.

**Comment by Danack** [comment] 2016-11-28 11:54
> Time for a new version

Probably.

I will take Wednesday afternoon off work to work on the Imagick issues that are known, and do another RC candidate that contain those things.

I would also refer anyone giving thumbs up here to this issue #162.

**Comment by dzuelke** [comment] 2016-11-28 13:25
Cool thanks @danack!

It might be enough for now to just roll out a minor update with the 7.1 build fix; other bugs can then be fixed separately without stressing you out ;)

**Comment by holtkamp** [comment] 2016-12-12 21:56
@dzuelke this currently "blocks" usage of PHP 7.1 + Imagick on Heroku. Maybe Heroku can sponsor some development capacity on helping @Danack out a bit?

**Comment by Danack** [comment] 2016-12-12 23:49
fyi I'm waiting to hear from Jan-E whether the fix I committed for the compile problem he noted [here](https://github.com/mkoppanen/imagick/commit/b9a092bec30d3562d1562b4d1032e61acfb2af1b) is correct.


As for development capacity, I think what Imagick really needs are:

i) A developer who uses Imagick to help write more tests, as well as report issues upstream to the ImageMagick guys.

ii) I really need to acquire a Windows PC to be able to build and test the Windows version locally.

iii) Someone who uses Imagick to write more documentation.

iii) Someone with quite a bit of time to figure out what to do about the changes from ImageMagick 6 to 7. A lot of that time will actually just be writing more documentation, or transition guides for end users.

**Comment by holtkamp** [comment] 2017-01-04 15:09
@Danack it seems @Jan-E confirmed that your fix works for him?
https://github.com/mkoppanen/imagick/commit/b9a092bec30d3562d1562b4d1032e61acfb2af1b#commitcomment-20173193

**Comment by Jan-E** [comment] 2017-01-04 16:49
Yes, I did. And building it for PHP 7.1 in VC14 is no problem. See
https://www.apachelounge.com/viewtopic.php?t=6359
and for instance the phpinfo-output in
https://phpdev.toolsforresearch.com/php-7.1.0-Win32-VC14-x64.htm

I did not run the tests, though.

**Comment by holtkamp** [comment] 2017-01-04 20:12
Ok, nice! Not sure whether other open ends remain, but does this pave the way for a 3.4.3 stable as suggested by the issue opener?

**Comment by Danack** [comment] 2017-01-17 22:53
Sorry for the delay.

I just tagged 3.4.3RC2, which has a couple of small fixes from RC1.

If people could check that I haven't mucked something up, I'll release an official 3.4.3 towards the end of the week.

**Comment by dzuelke** [comment] 2017-01-18 14:41
Small thing @Danack: both RCs have a "stable" stability on PECL, while the current stable has a "beta". Maybe something to add as "watch out for that" to a release playbook, if there is one? :)

**Comment by Danack** [comment] 2017-01-18 18:27
> a release playbook, if there is one?

![noideawhatimdoing](https://cloud.githubusercontent.com/assets/1505719/22077076/9a4715e8-ddaa-11e6-86a4-c471ca54c5e0.jpg)

Yeah - I screwed that up previously.

My understanding is that just leaving the stability as 'stable' for the time being would be the best + simplest approach, as versions that have RC in the title are considered not entirely stable by the pecl installer. Although that's not strictly following the standard, it is the path I'm least likely to muck up, I think.

If I ever get to making a version 4, which would have significant api cleanup - for that it would be appropriate to go through alpha/beta and RCs.

**Comment by holtkamp** [comment] 2017-01-20 07:54
I use brew to install it, which does not seems to have picked up the update:

```
➜  ~ brew info php71-imagick
homebrew/php/php71-imagick: stable 3.4.3RC1 (bottled), HEAD
Provides a wrapper to the ImageMagick library.
https://pecl.php.net/package/imagick
/usr/local/Cellar/php71-imagick/3.4.3RC1_3 (3 files, 308.6K) *
  Built from source on 2017-01-19 at 15:01:48
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php71-imagick.rb
```

**Comment by Danack** [comment] 2017-01-20 12:08
@holtkamp please discuss brew issues in the brew issue tracker rather than here.

**Comment by holtkamp** [comment] 2017-01-20 12:25
@Danack yeah I will, just posted it to indicate that I can't test the new RC just yet... (could have mentioned that, sorry 😄 )

**Comment by holtkamp** [comment] 2017-01-24 22:23
>If people could check that I haven't mucked something up, I'll release an official 3.4.3 towards the end of the week.

Not a pro on this, but the test-suite of https://github.com/Intervention/image contains some Imagick tests which fail with a segmentation fault...

```
git clone https://github.com/Intervention/image
cd image
composer install
vendor/bin/phpunit --debug tests/ImagickColorTest.php
```

Seems to be in https://github.com/Intervention/image/blob/2ab7e97d080ee8460ccfa7c5beadc0cade08013e/tests/ImagickColorTest.php#L19-L22

Environment:
- PHP 7.1.1 (cli) (built: Jan 22 2017 11:19:15) ( NTS )
- imagick module version 	3.4.3RC2
- imagick classes 	Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
- Imagick compiled with ImageMagick version 	ImageMagick 7.0.4-4 Q16 x86_64 2017-01-15 http://www.imagemagick.org
- Imagick using ImageMagick library version 	ImageMagick 7.0.4-5 Q16 x86_64 2017-01-21 http://www.imagemagick.org
- ImageMagick release date 	2017-01-21
- ImageMagick number of supported formats: 	219 

Commenting out ```testGetRedGreenBlueAlphaValue``` make that test run properly again...

**Comment by Danack** [comment] 2017-01-24 23:48
@holtkamp Please open a new ticket in this repo with a stack trace of the segfault you're seeing using something like valgrind running the test through `valgrind vendor/bin/phpunit --debug tests/ImagickColorTest.php`.

If you're not able to generate a stack trace, please open a ticket in the intervention repo and ask for their help to reproduce this issue. Feel free to ping me to weigh in on that ticket - however I don't compile Imagick on OSX. 

On the face of it this has less than a 50% chance of being a problem Imagick.

> the test-suite of https://github.com/Intervention/image contains some Imagick tests

Actually - it doesn't really. The code from the failing test:

```
    $c = new Color;
    $c->pixel = Mockery::mock('ImagickPixel');
    $c->pixel->shouldReceive('getcolorvalue')->with(Imagick::COLOR_GREEN)->andReturn(0.0470588235294);
    $this->assertEquals(12, $c->getGreenValue());
```

is creating a mock ImagickPixel object and defining what method should be called on it, and what the return value should be. It isn't (or maybe shouldn't be) actually interacting with an ImagickPixel object - which is why that test can run without passing a colour value to the constructor of the ImagickPixel object.

If there's a segfault happening, it has equal chance of occurring due to PHP, xdebug or imagick.

Finally......
> Imagick compiled with ImageMagick version ImageMagick 7.0.4-4 Q16 x86_64 2017-01-15 
> Imagick using ImageMagick library version ImageMagick 7.0.4-5 Q16 x86_64 2017-01-21 

Imagick is really meant to only be used against the exact version of ImageMagick it was compiled against. The ImageMagick guys follow semver even less than I do. 

There is a check in place in Imagick to make sure it's being run against the same Major.Minor.Bug version that it was compiled against. It would be quite interesting to see if your segfault goes away when running Imagick against the exact version it was compiled against.

**Comment by edmeister** [comment] 2017-01-25 10:33
Any ETA on 3.4.3-stable? We're withholding our upgrade to PHP 7.1.

**Comment by remicollet** [comment] 2017-01-25 10:42
@edmeister AFAIK, there is going to have  a 3.4.3RC4 (very soon)

**Comment by holtkamp** [comment] 2017-01-25 11:28
>Please open a new ticket in this repo with a stack trace
Thanks for the detailed response, this is where my "I am no pro on this" excuse comes in handy 😄 . I guess the issue you suggested is already created: https://github.com/mkoppanen/imagick/issues/195

Standing by for now...

**Comment by Danack** [comment] 2017-01-25 11:28
@edmeister and @holtkamp So you've got some time on your hands? If so: https://github.com/mkoppanen/imagick/issues/162

**Comment by Danack** [comment] 2017-02-01 23:32
['ave at it.](http://pecl.php.net/package/imagick/3.4.3)

**Closed by Danack** 2017-02-01 23:32 UTC

**Comment by dzuelke** [comment] 2017-02-01 23:41
Love it! Good stuff!
